name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        provenance: true
        sbom: true          
